media: media
content:
  - name: articles
    label: Events
    type: collection
    path: _articles
    view:
      fields: [ layout, title, tag, date, permalink, order ]
    fields:
      - { name: layout, type: string, hidden: false, default: article, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: tag , label: Tag, required: true, type: select, options: { values: [ "visitors", "members", "youth", "men", "women", "seniors", "kids", "all" ] } }
      - { name: permalink, label: Url, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: order, label: Order, type: number }
  - name: events
    label: Events
    type: collection
    path: _events
    view:
      fields: [ layout, title, tag, date, permalink, order ]
    fields:
      - { name: layout, type: string, hidden: false, default: event, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: tag , label: Tag, required: true, type: select, options: { values: [ "visitors", "members", "youth", "men", "women", "seniors", "kids", "all" ] } }
      - { name: date, label: Date, type: date }
      - { name: permalink, label: Url, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: order, label: Order, type: number }
  - name: ministries
    label: Ministries
    type: collection
    path: _ministries
    view:
      fields: [ layout, title, banner, order ]
    fields:
      - { name: layout, type: string, hidden: false, default: ministry, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: banner, label: Banner image, type: image }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: team
    label: Team
    type: collection
    path: _team
    view:
      fields: [ layout, name, role, image, order, banner ]
    fields:
      - { name: layout, type: string, hidden: false, default: staff, required: true }
      - { name: name , label: Name, type: string, required: true }
      - { name: role , label: Role, type: string, required: true }
      - { name: banner , label: Show in Lead, type: boolean, required: true }
      - { name: image, label: Cover image, type: image }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: missions
    label: Missions
    type: collection
    path: _missions
    view:
      fields: [ layout, name, location, image, order ]
    fields:
      - { name: layout, type: string, hidden: false, default: mission, required: true }
      - { name: name , label: Name, type: string, required: true }
      - { name: location , label: Location, type: string, required: true }
      - { name: image, label: Image, type: image }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ cover, title ]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: cover, label: Cover image, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: categories, label: Categories, type: select, options: { values: [ "misc", "junk" ] } }
      - { name: author, label: Authors, type: string, list: true }
      - { name: meta, label: Meta, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: Jekyll config
    type: file
    path: _config.yml
    fields:
      - { name: title, label: Title, type: string, required: true }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: email, label: Email, type: string, pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" }
      - { name: description, label: Description, type: string }
      - { name: plugins, label: Plugins, type: string, list: true }
