media: media
content:
  - name: events
    label: Events
    type: collection
    path: _events
    view:
      fields: [ title, tag, order ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: tag , label: Tag, required: true, type: select, options: { values: [ "visitors", "youth", "men", "women", "seniors", "kids", "all" ] } }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }
      - { name: order, label: Order, type: number }
  - name: ministries
    label: Ministries
    type: collection
    path: _ministries
    view:
      fields: [ title, order ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: banner, label: Banner image, type: image }
      - { name: order, label: Order, type: number }
  - name: team
    label: Team
    type: collection
    path: _team
    view:
      fields: [ image, name, order ]
    fields:
      - { name: name , label: Name, type: string, required: true }
      - { name: role , label: Role, type: string, required: true }
      - { name: image, label: Cover image, type: image }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: missions
    label: Missions
    type: collection
    path: _missions
    view:
      fields: [ image, location, order ]
    fields:
      - { name: name , label: Name, type: string, required: true }
      - { name: location , label: Location, type: string, required: true }
      - { name: image, label: Image, type: image }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ cover, title ]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: cover, label: Cover image, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: categories, label: Categories, type: select, options: { values: [ "misc", "junk" ] } }
      - { name: author, label: Authors, type: string, list: true }
      - { name: meta, label: Meta, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: Jekyll config
    type: file
    path: _config.yml
    fields:
      - { name: title, label: Title, type: string, required: true }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: email, label: Email, type: string, pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" }
      - { name: description, label: Description, type: string }
      - { name: theme, label: Theme, type: string }
      - { name: plugins, label: Plugins, type: string, list: true }
      - { name: header_pages, label: Header pages, type: string, list: true }
      - name: minima
        label: Minima settings
        description: Minima specific settings, which are only available from Minima 3.0 onward.
        type: object
        fields:
          - { name: skin, label: Skin, type: select, options: { values: [ "classic", "dark", "auto", "solarized-light", "solarized-dark", "solarized" ] } }
