title: Trinity Anglican Church - South Christchurch

author:
  name: Trinity South Christchurch
  email: info@trinitysc.nz

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  We are an Anglican evangelical Church made up of Christians of all ages and from all walks of life.
  Our desire is to hear Jesus speak, see Jesus work, and share Jesus’ love.

collections:
  articles:
    output: true
  team:
    output: true
  members:
    output: true
  ministries:
    output: true
  events:
    output: true
    permalink: "/events/:name"
  missions:
    output: true
  series:
    output: true

excerpt_separator: <!--excerpt end-->

# Allow pages with a data attribute to be displayed even if the date is in the future
# (Default is to return a 404)
future:
  true

plugins:
  - jekyll-feed
  - jekyll-seo-tag



